language: python
python:
  - "3.6"    
services:
  - mysql
env:
  -DJANGO=2.1 DB=mysql
install:
  - cd Upload-django-module 
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py runserver
  - fuser -k 8000/tcp
  - python manage.py test
