language: python
    python:
      - "3.6"
    
    services:
      - mysql
    
    env:
      -DJANGO=2.1 DB=mysql
    
    install:
      - pip install -r requirements.txt
    
    before_script:
      - mysql -e 'create database test;' -u root
    
    script: 
      - cd Upload-django-module 
      - python manage.py runserver
      - python manage.py test
